@baseUrl = http://localhost:3000

# MESSAGES
### Get all
GET {{baseUrl}}/messages

### Get one
GET {{baseUrl}}/messages/1

### 
# @name CreateMessage
POST {{baseUrl}}/messages/
Content-Type: application/json

{
    "message":"This is a test message",
    "user":"Jeremy"
}

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### OtherRoute

# @name OtherRoute
GET {{baseUrl}}/home/example

### ConceptsManuallyMade

# @name ConceptsManualHome
GET {{baseUrl}}/concepts-manual

### ConceptsAutomaticallyMade

# @name ConceptsAutomaticHome
GET {{baseUrl}}/concepts-automatic