@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.accessToken}}

# MESSAGES
### Get all
GET {{baseUrl}}/messages/
?limit=10
&offset=0
Authorization: Bearer 123456

### Get one
GET {{baseUrl}}/messages/11

### 
# @name CreateMessage
POST {{baseUrl}}/messages/
Content-Type: application/json

{
    "text": "Fanyos",
    "fromId": 10,
    "toId": 9
}

### Update a message
PATCH {{baseUrl}}/messages/11
Content-Type: application/json

{
    "text": "Updated to Fanyos again",
    "read": true
  }

### Deletes a message
DELETE {{baseUrl}}/messages/2


# USERS
### Get all
GET {{baseUrl}}/users/
Authorization: Bearer {{authToken}}

### Get one
GET {{baseUrl}}/users/2
Authorization: Bearer {{authToken}}

### Create
# @name CreateUser
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "email": "higor.sarcovia@gmail.com",
    "name": "Higor",
    "password": "123456"
}


### Update an user
PATCH {{baseUrl}}/users/10
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "name": "Jeremy Paule",
    "password": "123456"
  }


### Delete
# @name DeleteUser
DELETE {{baseUrl}}/users/12
Authorization: Bearer {{authToken}}

#AUTH
### Requests a login
# @name authenticate
POST {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "jeremy.paulepereira@gmail.com",
  "password": "123456"
}



### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### OtherRoute

# @name OtherRoute
GET {{baseUrl}}/home/example

### ConceptsManuallyMade

# @name ConceptsManualHome
GET {{baseUrl}}/concepts-manual

### ConceptsAutomaticallyMade

# @name ConceptsAutomaticHome
GET {{baseUrl}}/concepts-automatic