@baseUrl = http://localhost:3000

# MESSAGES
### Get all
GET {{baseUrl}}/messages/
?limit=100
&offset=10

### Get one
GET {{baseUrl}}/messages/2

### 
# @name CreateMessage
POST {{baseUrl}}/messages/
Content-Type: application/json

{
    "text": "Test message",
    "from": "Jeremy",
    "to": "Joana",
    "read": false,
    "date": "2024-09-09T12:13:41.039Z"
  }

### Update a message
PATCH {{baseUrl}}/messages/2
Content-Type: application/json

{
    "text": "Updated message",
    "from": "Joana",
    "to": "Jeremy",
    "read": false,
    "date": "2024-09-09T12:13:41.039Z"
  }

### Deletes a message
DELETE {{baseUrl}}/messages/2




### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### OtherRoute

# @name OtherRoute
GET {{baseUrl}}/home/example

### ConceptsManuallyMade

# @name ConceptsManualHome
GET {{baseUrl}}/concepts-manual

### ConceptsAutomaticallyMade

# @name ConceptsAutomaticHome
GET {{baseUrl}}/concepts-automatic